_target_: src.datamodules.voxPopuli_datamodule.VoxPopuliDataModule

data_dir: ${data_dir}
batch_size: 16
num_workers: 0
pin_memory: False
manifest_dir: ../slue-toolkit/manifest/slue-voxpopuli/nlp_ner
vocab_path: ${vocab_path}
model_type: deberta-base
label_type: raw
